/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SignupConfirmRouteImport } from './routes/signup.confirm'
import { Route as PropertyNewRouteImport } from './routes/property.new'
import { Route as DashboardTenantRouteImport } from './routes/dashboard.tenant'
import { Route as DashboardOwnerRouteImport } from './routes/dashboard.owner'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as PropertyIdIndexRouteImport } from './routes/property.$id.index'
import { Route as VisitsManagePropertyIdRouteImport } from './routes/visits.manage.$propertyId'
import { Route as VisitsBookPropertyIdRouteImport } from './routes/visits.book.$propertyId'
import { Route as PropertyIdStatsRouteImport } from './routes/property.$id.stats'
import { Route as PropertyIdEditRouteImport } from './routes/property.$id.edit'
import { Route as MessagesPropertyIdOtherIdRouteImport } from './routes/messages.$propertyId.$otherId'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupConfirmRoute = SignupConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => SignupRoute,
} as any)
const PropertyNewRoute = PropertyNewRouteImport.update({
  id: '/property/new',
  path: '/property/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantRoute = DashboardTenantRouteImport.update({
  id: '/dashboard/tenant',
  path: '/dashboard/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOwnerRoute = DashboardOwnerRouteImport.update({
  id: '/dashboard/owner',
  path: '/dashboard/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdIndexRoute = PropertyIdIndexRouteImport.update({
  id: '/property/$id/',
  path: '/property/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsManagePropertyIdRoute = VisitsManagePropertyIdRouteImport.update({
  id: '/visits/manage/$propertyId',
  path: '/visits/manage/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsBookPropertyIdRoute = VisitsBookPropertyIdRouteImport.update({
  id: '/visits/book/$propertyId',
  path: '/visits/book/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdStatsRoute = PropertyIdStatsRouteImport.update({
  id: '/property/$id/stats',
  path: '/property/$id/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdEditRoute = PropertyIdEditRouteImport.update({
  id: '/property/$id/edit',
  path: '/property/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesPropertyIdOtherIdRoute =
  MessagesPropertyIdOtherIdRouteImport.update({
    id: '/messages/$propertyId/$otherId',
    path: '/messages/$propertyId/$otherId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cgu': typeof CguRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tokens': typeof TokensRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/property/new': typeof PropertyNewRoute
  '/signup/confirm': typeof SignupConfirmRoute
  '/blog/': typeof BlogIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/messages/$propertyId/$otherId': typeof MessagesPropertyIdOtherIdRoute
  '/property/$id/edit': typeof PropertyIdEditRoute
  '/property/$id/stats': typeof PropertyIdStatsRoute
  '/visits/book/$propertyId': typeof VisitsBookPropertyIdRoute
  '/visits/manage/$propertyId': typeof VisitsManagePropertyIdRoute
  '/property/$id/': typeof PropertyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cgu': typeof CguRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tokens': typeof TokensRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/property/new': typeof PropertyNewRoute
  '/signup/confirm': typeof SignupConfirmRoute
  '/blog': typeof BlogIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/messages/$propertyId/$otherId': typeof MessagesPropertyIdOtherIdRoute
  '/property/$id/edit': typeof PropertyIdEditRoute
  '/property/$id/stats': typeof PropertyIdStatsRoute
  '/visits/book/$propertyId': typeof VisitsBookPropertyIdRoute
  '/visits/manage/$propertyId': typeof VisitsManagePropertyIdRoute
  '/property/$id': typeof PropertyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cgu': typeof CguRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tokens': typeof TokensRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/property/new': typeof PropertyNewRoute
  '/signup/confirm': typeof SignupConfirmRoute
  '/blog/': typeof BlogIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/messages/$propertyId/$otherId': typeof MessagesPropertyIdOtherIdRoute
  '/property/$id/edit': typeof PropertyIdEditRoute
  '/property/$id/stats': typeof PropertyIdStatsRoute
  '/visits/book/$propertyId': typeof VisitsBookPropertyIdRoute
  '/visits/manage/$propertyId': typeof VisitsManagePropertyIdRoute
  '/property/$id/': typeof PropertyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/cgu'
    | '/compare'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/kyc'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tokens'
    | '/admin/blog'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/property/new'
    | '/signup/confirm'
    | '/blog/'
    | '/messages/'
    | '/messages/$propertyId/$otherId'
    | '/property/$id/edit'
    | '/property/$id/stats'
    | '/visits/book/$propertyId'
    | '/visits/manage/$propertyId'
    | '/property/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/cgu'
    | '/compare'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/kyc'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tokens'
    | '/admin/blog'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/property/new'
    | '/signup/confirm'
    | '/blog'
    | '/messages'
    | '/messages/$propertyId/$otherId'
    | '/property/$id/edit'
    | '/property/$id/stats'
    | '/visits/book/$propertyId'
    | '/visits/manage/$propertyId'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/cgu'
    | '/compare'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/kyc'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tokens'
    | '/admin/blog'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/property/new'
    | '/signup/confirm'
    | '/blog/'
    | '/messages/'
    | '/messages/$propertyId/$otherId'
    | '/property/$id/edit'
    | '/property/$id/stats'
    | '/visits/book/$propertyId'
    | '/visits/manage/$propertyId'
    | '/property/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CguRoute: typeof CguRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TokensRoute: typeof TokensRoute
  AdminBlogRoute: typeof AdminBlogRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardOwnerRoute: typeof DashboardOwnerRoute
  DashboardTenantRoute: typeof DashboardTenantRoute
  PropertyNewRoute: typeof PropertyNewRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  MessagesPropertyIdOtherIdRoute: typeof MessagesPropertyIdOtherIdRoute
  PropertyIdEditRoute: typeof PropertyIdEditRoute
  PropertyIdStatsRoute: typeof PropertyIdStatsRoute
  VisitsBookPropertyIdRoute: typeof VisitsBookPropertyIdRoute
  VisitsManagePropertyIdRoute: typeof VisitsManagePropertyIdRoute
  PropertyIdIndexRoute: typeof PropertyIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/confirm': {
      id: '/signup/confirm'
      path: '/confirm'
      fullPath: '/signup/confirm'
      preLoaderRoute: typeof SignupConfirmRouteImport
      parentRoute: typeof SignupRoute
    }
    '/property/new': {
      id: '/property/new'
      path: '/property/new'
      fullPath: '/property/new'
      preLoaderRoute: typeof PropertyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/dashboard/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/owner': {
      id: '/dashboard/owner'
      path: '/dashboard/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof DashboardOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id/': {
      id: '/property/$id/'
      path: '/property/$id'
      fullPath: '/property/$id/'
      preLoaderRoute: typeof PropertyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/manage/$propertyId': {
      id: '/visits/manage/$propertyId'
      path: '/visits/manage/$propertyId'
      fullPath: '/visits/manage/$propertyId'
      preLoaderRoute: typeof VisitsManagePropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/book/$propertyId': {
      id: '/visits/book/$propertyId'
      path: '/visits/book/$propertyId'
      fullPath: '/visits/book/$propertyId'
      preLoaderRoute: typeof VisitsBookPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id/stats': {
      id: '/property/$id/stats'
      path: '/property/$id/stats'
      fullPath: '/property/$id/stats'
      preLoaderRoute: typeof PropertyIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id/edit': {
      id: '/property/$id/edit'
      path: '/property/$id/edit'
      fullPath: '/property/$id/edit'
      preLoaderRoute: typeof PropertyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$propertyId/$otherId': {
      id: '/messages/$propertyId/$otherId'
      path: '/messages/$propertyId/$otherId'
      fullPath: '/messages/$propertyId/$otherId'
      preLoaderRoute: typeof MessagesPropertyIdOtherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignupRouteChildren {
  SignupConfirmRoute: typeof SignupConfirmRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupConfirmRoute: SignupConfirmRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CguRoute: CguRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TokensRoute: TokensRoute,
  AdminBlogRoute: AdminBlogRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardOwnerRoute: DashboardOwnerRoute,
  DashboardTenantRoute: DashboardTenantRoute,
  PropertyNewRoute: PropertyNewRoute,
  BlogIndexRoute: BlogIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  MessagesPropertyIdOtherIdRoute: MessagesPropertyIdOtherIdRoute,
  PropertyIdEditRoute: PropertyIdEditRoute,
  PropertyIdStatsRoute: PropertyIdStatsRoute,
  VisitsBookPropertyIdRoute: VisitsBookPropertyIdRoute,
  VisitsManagePropertyIdRoute: VisitsManagePropertyIdRoute,
  PropertyIdIndexRoute: PropertyIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
